# Generated by Django 4.0.5 on 2022-07-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_alter_post_options_post_created_post_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
