# Generated by Django 4.0.5 on 2022-07-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_alter_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
