# Generated by Django 4.0.5 on 2022-07-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0021_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
