# Generated by Django 4.0.5 on 2022-07-29 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0026_alter_post_likes_alter_post_publish_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 14, 47, 24, 808253, tzinfo=utc)),
        ),
    ]
